### ISSUE TITLE
Help with deploying InvoiceNinja 5 on Rpi4

### ISSUE THREAD

**Issue by shashank-brdj** [invoiceninja/dockerfiles#442] opened 2022-05-26 19:27 UTC
Greetings Devs!
First off, thank you for this value rich product. Truely amazing software!
I love self hosting FOSS.
I am really trying hard to get Invoice ninja up and running using portainer on my raspberry pi 4.

My setup

**Hardware**: Raspberry Pi 4
**OS**: Ubuntu Server 20.04 LTS
**Env**: Docker
**GUI**: Portainer
**Proxy**: Nginx Reverse Proxy (manual)

I am trying to find a working **docker-compose** file, but i'm not successful.

I would really appreciate it if someone could provide me a working
- docker compose file along with maraidb section inside it
- Nginx reverse proxy script to use it along with a domain attached.

And yes, i want to mount the data to a persistent volume.

It would be amazing if anyone could help me in deploying the same.

Thank you! 🙌

**Comment by turbo124** [comment] 2022-05-26 21:11
duplicate of #183

**Closed** 2022-08-31 22:00 UTC
Labels: duplicate
