### ISSUE TITLE
Update to latest version (4.5.14) not propagated on hub.docker.com

### ISSUE THREAD

**Issue by Mzngit** [invoiceninja/dockerfiles#104] opened 2019-07-22 21:58 UTC
Any way to automate this, or does it have to be manual for every update?
Thanks.

**Comment by lalop** [comment] 2019-07-23 07:33
it should be automated when the tag is created, I think the issue is on the docker hub since the alpine tag was created https://hub.docker.com/r/invoiceninja/invoiceninja/tags

**Comment by lalop** [comment] 2019-07-23 07:33
I will forced it for now
There is an other issue to make this image official https://github.com/invoiceninja/dockerfiles/issues/69

**Comment by lalop** [comment] 2019-07-23 08:59
it was linked to this https://github.com/docker-library/php/issues/865https://github.com/docker-library/php/issues/865 
it's fixed now

**Closed by lalop** 2019-07-23 08:59 UTC
