### ISSUE TITLE
Unable to complete fresh install via docker compose

### ISSUE THREAD

**Issue by schmittg25** [invoiceninja/dockerfiles#305] opened 2021-03-24 15:24 UTC
Using the Quickstart V5 launch settings at https://github.com/invoiceninja/dockerfiles I am unable to get invoice ninja to run

- I run the git clone 
- I go edit the env file
- - I change the URL to http://invoices.MYFQDN.com:8003/
- - I put in my APP_Key (with the base64)
- I go edit the docker compose.yml
- - I change the port for nginx to - "8003:80" (I already have something on the docker host running on port 80 anyway)
- - I remove the extra_hosts: and - "in5.localhost:192.168.0.124 " #host and ip lines from the server, app and db
- I issue the sudo chown -R 1500:1500 docker/app
- I run docker-compose up
- It appears everything is ready.
- Open browser to http://invoices.MYFQDN.com:8003
- - Get a 403 Forbidden error page from nginx
- - see the following errors: 
- - - server_1  | 2021/03/24 15:21:07 [error] 23#23: *2 "/var/www/app/public/index.php" is forbidden (13: Permission denied), client: 192.168.1.106, server: _, request: "GET / HTTP/1.1", host: "invoices.FQDN.com:8003"
server_1  | 192.168.1.106 - - [24/Mar/2021:15:21:07 +0000] "GET / HTTP/1.1" 403 555 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36 Edg/89.0.774.57" "-"
server_1  | 2021/03/24 15:21:07 [error] 23#23: *2 open() "/var/www/app/public/favicon.ico" failed (13: Permission denied), client: 192.168.1.106, server: _, request: "GET /favicon.ico HTTP/1.1", host: "invoices.FQDN.com:8003", referrer: "http://invoices.FQDN.com:8003/"

I can recreate this over and over again, so I know I must be doing something wrong. Can anyone help?

**Comment by schmittg25** [comment] 2021-03-24 15:27
A couple extra notes, I've removed my FQDN from the info I posted, and 192.168.1.106 is the client on my lan that I am trying to access invoice ninja from.

**Comment by lwj5** [comment] 2021-03-24 15:41
Is this on linux? If it is I might have to spin up one to test it since I'm working on a mac

**Comment by schmittg25** [comment] 2021-03-24 16:11
Yes. PhantomOS on ESXi to be exact.

**Comment by lwj5** [comment] 2021-03-24 16:11
can you switch to nginx-user branch on this git and try docker-compose up

**Comment by schmittg25** [comment] 2021-03-24 16:25
whats the best way to do that? I'm a little new to docker.

**Comment by lwj5** [comment] 2021-03-24 16:29
no worries, just run git pull on the git directory. if everything goes well follow the steps above again.

At the worst, just delete your current directory and do a git clone again.

**Comment by schmittg25** [comment] 2021-03-24 16:32
so I tried git pull https://github.com/invoiceninja/dockerfiles and I got a fatal: not a git repository (or any of the parent directories) .git 

Sorry for being a newb at this.

**Comment by schmittg25** [comment] 2021-03-24 16:33
I just did a git clone again, made the same changes as above (switch port to 8003 from 80, removed the extra_hosts lines, and put in my appkey) and its doing the exact same thing again with the forbidden 403

**Comment by lwj5** [comment] 2021-03-24 16:38
My bad. could you git clone https://github.com/lwj5/dockerfiles.git , i merged the changes to the wrong repo

**Comment by schmittg25** [comment] 2021-03-24 16:51
This seems to be even worse, I can't even get a 403 error. I see dockerfiles_server_1 and dockerfiles_app_1 exited with code 1. I see a bunch of /etc/nginx/nginx.con failed 13: permission denied in the console.

**Comment by schmittg25** [comment] 2021-03-24 17:01
so I went back to the normal branch (git clone https://github.com/invoiceninja/dockerfiles.git) and made my normal changes.

I think did a `chmod -R 777 docker/app` and boom, I can launch it from http://invoices.fqdn.com:8003. I know this isn't right, but it's got to be something with permissions somewhere.....

**Comment by lwj5** [comment] 2021-03-24 17:25
I'll spin up a Linux tomorrow to test this. so far it's working on both my windows and mac machines.

**Comment by schmittg25** [comment] 2021-03-24 17:37
Awesome thanks! Just to confirm the chown is 1500:1500 recursive to docker/app ?

**Comment by lwj5** [comment] 2021-03-25 03:10
I can't reproduce this on Ubuntu Linux. I can access the invoiceninja setup page with the following steps.

Steps:
1. git clone https://github.com/invoiceninja/dockerfiles.git
1. Put APP_Key in env
1. sudo chown -R 1500:1500 docker/app
1. `sudo docker-compose up`


I'm running docker 19.03.8

**Comment by schmittg25** [comment] 2021-03-25 15:55
so I did exactly that..... nothing more, nothing less. I stopped the container I had that was running on port 80 just to test.

And I am getting the exact same issue. (192.168.1.19 is the IPV4 address of my docker host)

I'm on docker 19.03.10

`server_1  | 192.168.1.106 - - [25/Mar/2021:15:44:41 +0000] "GET / HTTP/1.1" 403 555 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36" "-"
server_1  | 2021/03/25 15:44:41 [error] 23#23: *2 "/var/www/app/public/index.php" is forbidden (13: Permission denied), client: 192.168.1.106, server: _, request: "GET / HTTP/1.1", host: "192.168.1.19"
server_1  | 2021/03/25 15:44:41 [error] 23#23: *2 open() "/var/www/app/public/favicon.ico" failed (13: Permission denied), client: 192.168.1.106, server: _, request: "GET /favicon.ico HTTP/1.1", host: "192.168.1.19", referrer: "http://192.168.1.19/"
`

**Comment by schmittg25** [comment] 2021-03-25 16:00
So something interesting... it appears the docker container itself is changing the owner from 1500 to 82? See the screenshot here. Is this normal? 

https://i.imgur.com/xiC0mge.png

**Comment by lwj5** [comment] 2021-03-25 16:17
@schmittg25 yes that’s normal. Permissions are correct and the user and group is ok

let’s do some debugging, are you connected to invoice ninja slack? If not get an account here, http://slack.invoiceninja.com/ easier to text

**Comment by schmittg25** [comment] 2021-03-25 17:43
root@photon-machine [ ~/docker-invoice/dockerfiles/docker/app/public ]# docker ps
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS              PORTS                               NAMES
7614ee341522        nginx                          "/docker-entrypoint.…"   About an hour ago   Up About an hour    0.0.0.0:80->80/tcp                  dockerfiles_server_1
e7a91b4c4f0f        invoiceninja/invoiceninja:5    "docker-entrypoint /…"   About an hour ago   Up About an hour    9000/tcp                            dockerfiles_app_1
c2d35a4089aa        mysql:5                        "docker-entrypoint.s…"   About an hour ago   Up About an hour    33060/tcp, 0.0.0.0:3305->3306/tcp   dockerfiles_db_1
b4df4cea75f6        ghcr.io/linuxserver/freshrss   "/init"                  46 hours ago        Up 46 hours         443/tcp, 0.0.0.0:8080->80/tcp       freshrss
root@photon-machine [ ~/docker-invoice/dockerfiles/docker/app/public ]# docker exec -it 7614ee341522 bash
root@7614ee341522:/# id
uid=0(root) gid=0(root) groups=0(root)
root@7614ee341522:/# cd /var/www
root@7614ee341522:/var/www# ls -l
total 4
drwxr-xr-x 4 root root 4096 Mar 25 16:12 app
root@7614ee341522:/var/www# cd app
root@7614ee341522:/var/www/app# ls -l
total 8
drwxr-x--- 10 1500 82 4096 Mar 25 16:12 public
drwxr-x---  5 1500 82 4096 Mar 25 16:12 storage
root@7614ee341522:/var/www/app# cd public
root@7614ee341522:/var/www/app/public# ls -l
total 12816
drwxrwxr-x 6 1500 82    4096 Mar 22 22:59 assets
drwxrwxr-x 2 1500 82    4096 Mar 22 23:00 css
-rwxrwxr-x 1 1500 82   15086 Mar 22 22:58 favicon.ico
-rwxrwxr-x 1 1500 82    2700 Mar 22 22:58 favicon.png
-rwxrwxr-x 1 1500 82    8120 Mar 22 22:58 flutter_service_worker.js
drwxrwxr-x 2 1500 82    4096 Mar 22 22:59 icons
drwxrwxr-x 3 1500 82    4096 Mar 22 22:59 images
-rwxrwxr-x 1 1500 82    1850 Mar 22 22:58 index.php
drwxrwxr-x 5 1500 82    4096 Mar 22 22:59 js
drwxr-xr-x 2 1500 82    4096 Mar 22 22:59 logo
-rwxrwxr-x 1 1500 82 7931538 Mar 22 22:58 main.dart.js
-rwxrwxr-x 1 1500 82 5100101 Mar 22 22:58 main.dart.js.map
-rwxrwxr-x 1 1500 82     708 Mar 22 22:58 manifest.json
-rwxrwxr-x 1 1500 82    1941 Mar 22 23:00 mix-manifest.json
-rwxrwxr-x 1 1500 82      24 Mar 22 22:58 robots.txt
drwxrwxr-x 2 1500 82    4096 Mar 22 22:59 svg
drwxrwxr-x 4 1500 82    4096 Mar 22 22:59 vendor
-rw-r--r-- 1 1500 82       7 Mar 25 16:12 version
-rwxrwxr-x 1 1500 82      74 Mar 22 22:58 version.json
root@7614ee341522:/var/www/app/public# cat index.php
<?php

// your application code

/**
 * Laravel - A PHP Framework For Web Artisans
 *
 * @package  Laravel
 * @author   Taylor Otwell <taylor@laravel.com>
 */

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Register The Auto Loader
|--------------------------------------------------------------------------
|
| Composer provides a convenient, automatically generated class loader for
| our application. We just need to utilize it! We'll simply require it
| into the script here so that we don't have to worry about manual
| loading any of our classes later on. It feels great to relax.
|
*/

require __DIR__.'/../vendor/autoload.php';

/*
|--------------------------------------------------------------------------
| Turn On The Lights
|--------------------------------------------------------------------------
|
| We need to illuminate PHP development, so let us turn on the lights.
| This bootstraps the framework and gets it ready for use, then it
| will load up this application so that we can run it and send
| the responses back to the browser and delight our users.
|
*/

$app = require_once __DIR__.'/../bootstrap/app.php';

/*
|--------------------------------------------------------------------------
| Run The Application
|--------------------------------------------------------------------------
|
| Once we have the application, we can handle the incoming request
| through the kernel, and send the associated response back to
| the client's browser allowing them to enjoy the creative
| and wonderful application we have prepared for them.
|
*/

$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);


$response->send();

$kernel->terminate($request, $response);
root@7614ee341522:/var/www/app/public#

**Comment by schmittg25** [comment] 2021-03-25 17:43
Just ping'd you over on slack also

**Comment by lwj5** [comment] 2021-03-26 01:35
```
root@7614ee341522:/var/www/app# ls -l
total 8
drwxr-x--- 10 1500 82 4096 Mar 25 16:12 public
drwxr-x---  5 1500 82 4096 Mar 25 16:12 storage
```

This line is the issue. No read permission for anybody. 
On your server, do a `chmod` for both `public` and `storage` to `755` (non-recursive). 
Your `git clone` is removing the permissions for everybody. Which led to the `/etc/nginx/nginx.conf failed` as well.

That's was what running nginx as user 1500 would have solved. Could you just run the chmod on the 2 folders.

**Closed** 2021-03-26 09:36 UTC
