### ISSUE TITLE
php 7.2 issue when trying to export report as PDF

### ISSUE THREAD

**Issue by LouisParkin** [invoiceninja/dockerfiles#86] opened 2018-10-02 10:42 UTC
The issue with PHP 7.2, as logged here https://github.com/mpdf/mpdf/issues/616 afflicts my deployment, and I found that updating the dockerfile to base on php:7.0-fpm resolved the issue.

**Comment by LouisParkin** [comment] 2018-10-02 10:44
```
FROM php:7.0-fpm

MAINTAINER Samuel Laulhau <sam@lalop.co>

#####
# SYSTEM REQUIREMENT
#####
ENV PHANTOMJS phantomjs-2.1.1-linux-x86_64
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        zlib1g-dev git libgmp-dev unzip \
        libfreetype6-dev libjpeg62-turbo-dev libpng-dev \
        build-essential chrpath libssl-dev libxft-dev \
        libfreetype6 libfontconfig1 libfontconfig1-dev \
    && ln -s /usr/include/x86_64-linux-gnu/gmp.h /usr/local/include/ \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-configure gmp \
    && docker-php-ext-install iconv mbstring pdo pdo_mysql zip gd gmp opcache \
    && curl -o ${PHANTOMJS}.tar.bz2 -SL https://bitbucket.org/ariya/phantomjs/downloads/${PHANTOMJS}.tar.bz2 \
    && tar xvjf ${PHANTOMJS}.tar.bz2 \
    && rm ${PHANTOMJS}.tar.bz2 \
    && mv ${PHANTOMJS} /usr/local/share \
    && ln -sf /usr/local/share/${PHANTOMJS}/bin/phantomjs /usr/local/bin \
    && rm -rf /var/lib/apt/lists/*
    
# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
		echo 'opcache.memory_consumption=128'; \
		echo 'opcache.interned_strings_buffer=8'; \
		echo 'opcache.max_accelerated_files=4000'; \
		echo 'opcache.revalidate_freq=60'; \
		echo 'opcache.fast_shutdown=1'; \
		echo 'opcache.enable_cli=1'; \
} > /usr/local/etc/php/conf.d/opcache-recommended.ini

#####
# DOWNLOAD AND INSTALL INVOICE NINJA
#####

ENV INVOICENINJA_VERSION 4.5.5

RUN curl -o ninja.zip -SL https://download.invoiceninja.com/ninja-v${INVOICENINJA_VERSION}.zip \
    && unzip ninja.zip -d /var/www/ \
    && rm ninja.zip \
    && mv /var/www/ninja /var/www/app  \
    && mv /var/www/app/storage /var/www/app/docker-backup-storage  \
    && mv /var/www/app/public /var/www/app/docker-backup-public  \
    && mkdir -p /var/www/app/public/logo /var/www/app/storage \
    && touch /var/www/app/.env \
    && chmod -R 755 /var/www/app/storage  \
    && chown -R www-data:www-data /var/www/app/storage /var/www/app/bootstrap /var/www/app/public/logo /var/www/app/.env /var/www/app/docker-backup-storage /var/www/app/docker-backup-public\
    && rm -rf /var/www/app/docs /var/www/app/tests /var/www/ninja

######
# DEFAULT ENV
######
ENV LOG errorlog
ENV SELF_UPDATER_SOURCE ''
ENV PHANTOMJS_BIN_PATH /usr/local/bin/phantomjs


#use to be mounted into nginx for exemple
VOLUME /var/www/app/public

WORKDIR /var/www/app

COPY entrypoint.sh /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["php-fpm"]
```

**Comment by lalop** [comment] 2018-10-06 18:50
@hillelcoren this seems to be fixed in the next version of mpdf, any chance to have an updated of this dependency ?

**Comment by hillelcoren** [comment] 2018-10-06 18:54
Yes, we plan to update the library in the next major release.

**Comment by lalop** [comment] 2018-11-14 09:35
@LouisParkin the last image should fix this, can you confirm that please ?

**Comment by LouisParkin** [comment] 2018-11-14 09:54
@lalop would that just entail spinning up a new docker stack on the latest invoiceninja dockerhub image?  Or should I build new docker images based on the latest php7.2 container?

**Comment by lalop** [comment] 2018-11-14 09:56
just use the last image from dockerhub

**Comment by LouisParkin** [comment] 2018-11-14 09:58
Apologies for being pedantic... invoiceninja/invoiceninja:4.5.6 or invoiceninja/invoiceninja:latest ?

**Comment by lalop** [comment] 2018-11-14 10:01
It should be the same but using tag 4.5.6 while force docker to pull the last one

**Comment by LouisParkin** [comment] 2018-11-14 10:05
Gimme 20 minutes, I'll verify.

**Comment by LouisParkin** [comment] 2018-11-14 10:18
Nope. Not resolved. I do, however, now get a 500 returned, instead of a `Resource not found` error. Log attached.
[error.txt](https://github.com/invoiceninja/dockerfiles/files/2580229/error.txt)
![image](https://user-images.githubusercontent.com/11991882/48476321-68795f80-e807-11e8-8b4e-0cd1638e7d23.png)

**Comment by LouisParkin** [comment] 2018-11-14 10:30
Also to be noted, in 4.5.5 with php:7.0-fpm as base container, exporting reports as PDF used to work.  It seems that in 4.5.6, it is now broken (even with php:7.0-fpm as base instead of 7.2), so some change in invoiceninja broke something that wasn't in need of fixing.

**Comment by LouisParkin** [comment] 2018-11-14 10:35
I can confirm my previous comment.  I took the same deployment and downgraded back to 4.5.5 on php:7.0-fpm base image, and PDF exporting works once more.

**Comment by lalop** [comment] 2018-11-21 21:31
@hillelcoren are you aware of this error :
```
app_1   | [14-Nov-2018 10:15:08] WARNING: [pool www] child 12 said into stderr: "[2018-11-14 10:15:08] production.ERROR: ***PHPExcel_Writer_Exception*** [0] : /var/www/app/vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/PDF/mPDF.php [Line 34] => Unable to load PDF Rendering library  {"context":"PHP","user_id":1,"account_id":1,"user_name":"Admininstrator Accounts","method":"POST","user_agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36","locale":"en_GB","ip":"172.18.0.1","count":1,"is_console":"no","is_api":"no","db_server":"mysql","url":"reports"} []"
```

It seems that phpexcell need dompdf to work

**Comment by hillelcoren** [comment] 2018-11-22 08:05
Thanks, I'll take a look...

**Comment by LouisParkin** [comment] 2018-12-04 06:55
Hi @fredericnaud, these guys are working on it.  My workaround for the issue is to not use PHP 7.2 but PHP 7.0.

**Comment by hillelcoren** [comment] 2019-01-07 07:16
This should be fixed in v4.5.8

**Comment by LouisParkin** [comment] 2019-03-12 19:55
I notice the PDF option was removed in v4.5.11... backpedal... I am now building 4.5.10 on php7.0-fpm and that will be as far as I upgrade until v2... or until PDF is put back :-(

**Comment by hillelcoren** [comment] 2019-03-12 21:11
It looks like the problem is that the library we're using doesn't support PHP >= 7.1, once it's fixed we'll add the option back. 

If you're using PHP 7.0 you can manually add back the option by uncommenting this line:

https://github.com/invoiceninja/invoiceninja/blob/master/resources/views/reports/report_builder.blade.php#L588

**Comment by lalop** [comment] 2019-05-27 18:43
@hillelcoren any news on this point ?

**Comment by hillelcoren** [comment] 2019-05-28 05:48
No, I don't think it's likely we'll be able to reenable this in v1.

**Comment by LouisParkin** [comment] 2019-06-25 11:55
@hillelcoren apologies for using this ticket to ask a question not related to this ticket.  Is there a way for me to contact you directly?  I have questions about the REST API on invoiceninja.

**Comment by LouisParkin** [comment] 2019-06-25 11:55
> No, I don't think it's likely we'll be able to reenable this in v1.

Can I close this ticket then?

**Closed** 2020-04-24 15:21 UTC
