### ISSUE TITLE
Adding Raspberry Pi 32 or 64 Bit Image to Docker

### ISSUE THREAD

**Issue by pthoelken** [invoiceninja/dockerfiles#460] opened 2022-08-31 15:38 UTC
**What version of Invoice Ninja are you running? ie v4.5 / v5**
v5

**What environment are you running?**
Docker (would)

**Have you searched existing issues/requests?**
Yes

**Additional context**
Is there a way to create a Docker Image for Raspberry Pi 32 or 64 Bit? When I try to pull the invoiceninja image on my Raspberry Pi their told me there nothing found: 

`no matching manifest for linux/arm/v7 in the manifest list entries`

**Comment by turbo124** [comment] 2022-08-31 22:00
Duplicate of #183

**Closed by turbo124** 2022-08-31 22:00 UTC
Labels: duplicate
