### ISSUE TITLE
Update Issue from 3.4.1 to 3.4.2

### ISSUE THREAD

**Issue by SandroRaV** [invoiceninja/dockerfiles#54] opened 2017-07-17 09:43 UTC
I was updating from version 3.4.1 to version 3.4.2 with docker-compose stop than docker-compose pull && docker-compose up -d and get an error now when I try to access invoiceninja.

web error: Whoops, looks like something went wrong.

When I start without the -d option in docker-compose I see nothing suspicious.

What can I do?

**Comment by hillelcoren** [comment] 2017-07-17 10:26
Are there any details about the error in storage/logs/laravel-error.log

**Comment by SandroRaV** [comment] 2017-07-17 10:34
the log shows: [2017-07-17 10:33:33] production.ERROR: ***RuntimeException*** [0] : /var/www/app/bootstrap/cache/compiled.php [Line 7843] => No supported encrypter found. The cipher and / or key length are invalid.  {"context":"PHP","user_id":0,"account_id":0,"user_name":"","method":"GET","url":"https://domain","previous":"https://domian","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36","ip":"ip","count":2,"is_console":"no","is_api":"no","db_server":"mysql"} []

**Comment by hillelcoren** [comment] 2017-07-17 10:37
From the error the problem is likely related to your value for APP_KEY in the .env file

**Comment by SandroRaV** [comment] 2017-07-17 10:39
There is no APP_KEY value in my .env I try to find out if there was any

**Comment by SandroRaV** [comment] 2017-07-17 10:40
This file was not changed since months...

**Comment by hillelcoren** [comment] 2017-07-17 10:43
Is there a value for APP_CIPHER

**Comment by SandroRaV** [comment] 2017-07-17 10:44
There is no value for APP_CIPHER in the .env file

**Comment by hillelcoren** [comment] 2017-07-17 10:50
Maybe this will help...

https://github.com/invoiceninja/invoiceninja/issues/1573

**Comment by SandroRaV** [comment] 2017-07-17 10:53
Wow adding an APP_KEY to the .env file that is exactly 32 characters long, fixed the issue. Thank you

**Comment by SandroRaV** [comment] 2017-07-17 10:54
hm works only for the login page. when i try to login the same happens

**Comment by hillelcoren** [comment] 2017-07-17 10:56
Try using `SomeRandomStringSomeRandomString` as the APP_KEY

Note: this is insecure, the APP_KEY should be a random value.

**Comment by arubacao** [comment] 2017-07-17 11:15
How did this ever work without a APP_KEY?

**Comment by arubacao** [comment] 2017-07-17 11:17
@SandroRaV are you using the `latest` or `3.4.2` docker tag?

**Comment by SandroRaV** [comment] 2017-07-17 11:26
@hillelcoren that did not work with the somerandomstrin
@arubacao I am not suer why it did work but it did. Where do I see the docker tag?

**Comment by arubacao** [comment] 2017-07-17 15:06
depending on which start command you use.
However your command or docker-compose.yml somewhere includes the image name:
`invoiceninja/invoiceninja`
It is either

1. `invoiceninja/invoiceninja:3.4.2`
2. `invoiceninja/invoiceninja:latest` or `invoiceninja/invoiceninja` (defaults to latest)

**Comment by SandroRaV** [comment] 2017-07-17 15:54
it is only invoiceninja/invoiceninja so it defaults to latest. any way to get around this issue?

**Comment by hillelcoren** [comment] 2017-07-17 16:40
Have you updated the app before or is this the first time?

**Comment by SandroRaV** [comment] 2017-07-17 17:22
Yes, did 5-6 updates with the same procedure and no changes in the .env file and all of them did work

**Comment by arubacao** [comment] 2017-07-17 19:14
Try adding to your .env file:
```

**Comment by arubacao** [comment] 2017-07-17 19:17
Try adding to your .env file:
```
APP_KEY=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
APP_CIPHER=AES-256-CBC
```
and then restart the docker containers

**Comment by SandroRaV** [comment] 2017-07-17 19:24
added but still the same issue. I can login but the error stays the same

**Comment by arubacao** [comment] 2017-07-17 19:47
Still with the same issue `No supported encrypter found. The cipher and / or key length are invalid. ` ? 
Also try:

1. Flush cache
2. Kill the compiled files

At the very least you will get a more detailed call stack

**Comment by SandroRaV** [comment] 2017-07-17 20:03
looks like the error has changed:

[2017-07-17 19:50:08] production.ERROR: ***Illuminate\Contracts\Encryption\DecryptException*** [0] : /var/www/app/bootstrap/cache/compiled.php [Line 13310] => The MAC is invalid.  {"context":"PHP","user_id":1,"account_id":1,"user_name":"user ,"method":"POST","url":"https://domain/login","previous":"https://domain/login","user_agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:54.0) Gecko/20100101 Firefox/54.0","ip":"172.18.0.1","count":1,"is_console":"no","is_api":"no","db_server":"mysql"} []


what do you mean by flush cash / kill the comiled files?

**Comment by arubacao** [comment] 2017-07-17 20:11
go into the docker image (something like `docker exec -it invoiceninja_whatsoever_1 bash`and execute:
```
php artisan clear-compiled
php artisan cache:clear
php artisan config:clear
php artisan view:clear
```
This removes all cached files

**Comment by SandroRaV** [comment] 2017-07-18 10:00
okay that works for one login when I do this and then restart the container I am able to log in once. When I try to do this again I see the same error

**Comment by hillelcoren** [comment] 2017-07-18 10:06
Try commenting out these 6 lines of code:

https://github.com/invoiceninja/invoiceninja/blob/master/app/Listeners/HandleUserLoggedIn.php#L67

**Comment by SandroRaV** [comment] 2017-07-18 10:13
okay that works until I go for the Online Payment section in settings... When I klick them the same error appears

**Comment by hillelcoren** [comment] 2017-07-18 10:23
Thanks, that's helpful to know. It seems likely the APP_KEY value has changed. If it wasn't set initially it should be using the default value. I'm not sure why upgrading caused this problem.

Without the original APP_KEY value the app won't be able to decode the payment gateway settings. If you don't have any billing tokens stored the simplest fix would be to manually mark the data in account_gateways table as archived/deleted and then re-add the payment gateway.

**Comment by arubacao** [comment] 2017-07-18 10:36
@hillelcoren i guess this issue comes from my PR #52 
The base image is now php7.1 *without* mcrypt instead of php7.0 *with* mcrypt.
Mcrypt was blocking the php upgrade. Laravel doesn't require mcrypt anymore and 
> Relying on this function is highly discouraged. [link](http://php.net/manual/en/function.mcrypt-encrypt.php)

I tested everything with my own real data and it worked.
However, I was a bit confused that an APP_KEY was hardcoded into the [Dockerfile](https://github.com/invoiceninja/dockerfiles/blob/master/Dockerfile#L68), but since the APP_KEY was under 32 chars - and therefore shouldn't work - it didn't bother me too much.
But now i'm not so sure anymore as @SandroRaV stated that he never used a APP_KEY.

I didn't have time to test it, but my bestguess to replicate the issue:

1. Pull a docker image tagged > `3.4.2` (before my PR)
2. Do *NOT* use a .env file with an APP_KEY and APP_CIPHER
3. Create a user (so something is encrypted) 
4. Now pull the docker image tagged `latest` (after my PR)
5. error should occur 

So I guess this causes problems for people *NOT* using a proper APP_KEY and using the hardcoded one in the Dockerfile. Breaking an invoiceninja instance is of course a big issue, however using the hardcoded APP_KEY is also extremely risky.

I don't know about a good solution for this. Maybe some sort of re-encrypting the data with a proper APP_KEY

**Comment by SandroRaV** [comment] 2017-07-18 10:38
I do have tokens in the payment gateway part so I am interested into finding another way then deleting them if possible

**Comment by arubacao** [comment] 2017-07-18 10:38
@SandroRaV a quickfix would be to use a tagged version instead of the latest. Also remove the newly added APP_KEY

**Comment by SandroRaV** [comment] 2017-07-18 10:39
can I use 3.4.1?

**Comment by arubacao** [comment] 2017-07-18 10:40
should work up to `3.4.2`

**Comment by SandroRaV** [comment] 2017-07-18 10:43
it looks good with version 3.4.1 now.

**Comment by hillelcoren** [comment] 2017-07-18 10:55
I agree using the default is a bad idea but we also can't simply remove it. Please add back the default value so it continues to work for existing users. In our next release we'll create an Artisan command to change the APP_KEY and warn if the app is setup with a default value. 

FYI... my understanding is the APP_KEY is used to encrypt session data but not for checking the password on login. The app uses the APP_KEY to encrypt the payment gateway and banking credentials. We check the payment gateway settings on login which was causing the error.

**Comment by SandroRaV** [comment] 2017-07-18 10:56
so will the next version fix this for me?

**Comment by hillelcoren** [comment] 2017-07-18 10:58
You're currently using a default value for the APP_KEY, in the next version we'll try to make it possible to change it, this will improve the app's security. 

@arubacao Removing mcrypt may be a problem as well.
@lalop What do you think?

**Comment by arubacao** [comment] 2017-07-18 11:04
@hillelcoren I'll create a new PR to revert my breaking PR - after the fix it can be reapplied.

The config file app.php currently looks like this:
```

    'key' => env('APP_KEY', 'SomeRandomStringSomeRandomString'),
    'cipher' => env('APP_CIPHER', 'AES-256-CBC'),
```
https://github.com/invoiceninja/invoiceninja/blob/master/config/app.php#L85-L87

I think after the fix it should look like this:
```
    'key' => env('APP_KEY'),
    'cipher' => 'AES-256-CBC',
```
https://github.com/laravel/laravel/blob/5.2/config/app.php#L94-L96

Also no APP_KEY should be hardcoded anywhere in the Dockerfile

**Comment by hillelcoren** [comment] 2017-07-18 11:38
Sounds good, thanks!

**Comment by lalop** [comment] 2017-07-18 12:26
@SandroRaV The app should work if you use the tag 3.4.2, latest is more advanced. Generally it's better to tag you image and manually update the tag version when you want to make an update to avoid unexpected update on side container, I had some issue updating mysql like  taht ;)

@arubacao why don't just add back  `ENV APP_CIPHER rijndael-128` ?

**Comment by arubacao** [comment] 2017-07-18 13:02
If @hillelcoren writes an upgrade command, i'd recommend the default `AES-256-CBC`
It seems like the only 2 supported ciphers are `AES-256-CBC` & `AES-128-CBC` since Laravel 5.1 [link](https://github.com/laravel/framework/blob/5.1/src/Illuminate/Encryption/Encrypter.php#L52).
> RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

**Comment by arubacao** [comment] 2017-07-18 13:05
This sounds somewhat stupid but maybe mcrypt rijndael-128 == openssl AES-256-CBC

**Comment by lalop** [comment] 2017-07-20 07:13
So you have no choice, you will keep php 7.0 for now

**Comment by hillelcoren** [comment] 2017-07-25 18:53
I've checked in two changes:
- When logging in the app will check that APP_KEY isn't set to a default value
- Added an Artisan command to update the key and re-encrypt the data

These changes will be included with v3.6, I think it'd be best to wait until v3.7 to re-apply these changes.

**Comment by arubacao** [comment] 2017-07-25 21:13
sounds good to me 👍

**Comment by arubacao** [comment] 2017-07-30 13:36
@hillelcoren I just came across this repository: https://github.com/laravel/legacy-encrypter
> This encryption package provides support for the legacy Mcrypt encrypter used by Laravel 5.0 through 5.2. It is primarily intended to be used to migrate your data to the new OpenSSL based encrypter used in 5.1 through the latest release of Laravel.

Maybe this helps

**Comment by lalop** [comment] 2017-08-17 09:40
Hello @hillelcoren 
Your command can't work in a docker environment since the container is in readonly te application can't write to the `.env` file.
Instead the environment variable are real environment variable.
So for now the command output an error 

```
  [ErrorException]                                                                        
  file_get_contents(/var/www/app/.env): failed to open stream: No such file or directory 
```

Maybe the command could simply output the new key in this case and let the user update is variable ?

**Comment by hillelcoren** [comment] 2017-08-17 10:38
Thanks for letting me know, I'll take a look

**Comment by hillelcoren** [comment] 2017-08-18 06:37
FYI... I've checked in a fix for this.

**Closed** 2017-10-15 12:57 UTC
