### ISSUE TITLE
InvoiceNinja v5 on Raspberry Pi 4 (ARMv7)

### ISSUE THREAD

**Issue by kewngen** [invoiceninja/dockerfiles#183] opened 2020-08-11 22:09 UTC
There have been other mentions about IN on RPi, for example: #108 
I am still unable to get it to work. When I change the mysql image as mentioned in #108 I get the following error:
```
standard_init_linux.go:211: exec user process caused "exec format error"
```

And when I try to build the Dockerfile_5 I get:
```
URL: https://download.cypress.io/desktop/4.6.0?platform=linux&arch=ia32
Error: Failed downloading the Cypress binary.
Response code: 404
Response message: Not Found

----------

Platform: linux (Alpine Linux - 3.11.6)
Cypress Version: 4.6.0
[...]
The command '/bin/sh -c npm install' returned a non-zero code: 1
```

Anyone able to run IN v5 on a RPi 4? If so, please provide some instructions on how to make it work.

**Comment by dimkasta** [comment] 2020-09-18 13:43
Any progress with this? Currently I am getting 

```
standard_init_linux.go:219: exec user process caused: exec format error
```

**Comment by pixlguru** [comment] 2020-09-30 06:30
"Error: Failed downloading the Cypress binary."
cypress doesn't run on a raspberry pi because it is not available for _arm_

**Comment by horschdel** [comment] 2021-01-23 19:23
Any progress on getting Invoice Ninja to run in docker on Raspberry Pi 4?

**Comment by vsisl** [comment] 2021-02-22 14:34
I would also be interested in running Invoice Ninja in docker on RPi4.

**Comment by lwj5** [comment] 2021-03-25 13:31
Anyone interested in testing an ARM64 image?  Build passed but I’m not even sure whether it will work.

**Comment by tacticz** [comment] 2021-03-25 18:53
Hello,

It is very possible to have invoiceninja running on a Raspberry Pi 4, as I currently have it 😃 

### ARM64, ARMv8, aarch64
First it is perhaps important to specify that the Raspberry Pi 4 has an **ARM v8** based Cortex-A72 processor as is stated on the [official raspberrypi.org page](https://www.raspberrypi.org/products/raspberry-pi-4-model-b/specifications/), this is also the case for the Raspberry Pi 3 Model B, B+ and in later models of the Raspberry Pi 2 which are Cortex-A53 based ([see here](https://www.raspberrypi.org/documentation/hardware/raspberrypi/bcm2837/README.md)).
Consequently, all of those models **_should_** be usable for what is described hereunder, although I personally only tested this on a Raspberry Pi 4 B.
The terms **ARM 64**, **ARM v8** and **aarch64** are used interchangeably to describe this processor architecture.

### Re-building the docker image
It is necessary to re-built the invoiceninja (app) docker image on the Raspberry Pi itself because, during the build process, alpine will collect and compile packages for **aarch64**. Here is an extract of the build logs that explicitly shows that:
```
Step 8/38 : RUN set -eux;     apk add --no-cache     curl
 ---> Running in 4014925938eb
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/aarch64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/aarch64/APKINDEX.tar.gz
(1/4) Installing ca-certificates (20191127-r2)
(2/4) Installing nghttp2-libs (1.40.0-r1)
(3/4) Installing libcurl (7.67.0-r3)
(4/4) Installing curl (7.67.0-r3)
...
```
Also the PHP extensions install process will extract and compile for the targeted architecture:
```
### INSTALLING BUNDLED MODULE bcmath ###
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/aarch64/APKINDEX.tar.gz
(1/1) Installing .phpize-deps (20210325.115001)
OK: 335 MiB in 115 packages
...
checking build system type... aarch64-unknown-linux-musl
checking host system type... aarch64-unknown-linux-musl
checking target system type... aarch64-unknown-linux-musl
...
checking for ld used by cc... /usr/aarch64-alpine-linux-musl/bin/ld
checking if the linker (/usr/aarch64-alpine-linux-musl/bin/ld) is GNU ld... yes
checking for /usr/aarch64-alpine-linux-musl/bin/ld option to reload object files... -r
...
checking whether the cc linker (/usr/aarch64-alpine-linux-musl/bin/ld) supports shared libraries... yes
...
```
Re-building the docker image is quite easy, simply clone the invoiceninja/dockerfiles repo to your RasPi and `docker build` from the repo's root directory.
#### docker build command
```
$ sudo apt update
$ sudo apt install git
$ cd ~/home/pi/docker
$ git clone git@github.com:invoiceninja/dockerfiles
$ cd dockerfiles
$ docker build \
-f alpine/Dockerfile_v5 \
--build-arg INVOICENINJA_VERSION=5.1.31 \
-t ininja-aarch64:5.1.31 . \
2>&1 | tee dockerbuild.log
```
The last line `2>&1 | tee dockerbuild.log` stores the install logs to a file while still displaying the output to `stdout` and is not mandatory of course.

On my Raspberry Pi 4 (8G), the build process took about 32 minutes (YMCV)...

### Modifying `docker-compose.yml`
The included `docker-compose.yml` file uses the `mysql:5` docker image for the `db` container, although it is **not reported as `AMD 64` compatible** on [hub.docker.com](https://hub.docker.com/_/mysql).
Nevertheless, as MariaDB is the official mysql compatible open-source alternative, and it's image is **reported as `ARM 64` compatible** on [hub.docker.com](https://hub.docker.com/_/mariadb), we can substitute it to the `mysql:5` image used by default.
`mysql:5` is indeed v5.7.33, and as stated in the [MariaDB compatibility page](https://mariadb.com/kb/en/mariadb-vs-mysql-compatibility/#drop-in-compatibility-of-specific-mariadb-versions), MariaDB 10.4 function as limited drop-in replacements for MySQL 5.7, as far as InnoDB is concerned. Thus we will use the `mariadb:10.4` image.

#### Substitute images used in the `docker-compose.yml` file
Since we have our locally built `ininja-aarch64:5.1.31` docker image, we only have to substitute the images used for the `app` and `db` containers:
```
$ cd ~/home/pi/docker/dockerfiles
$ nano -l docker-compose.yml
...
  app:
    image: ininja-aarch64:5.1.31
...
  db:
    image: mariadb:10.4
```

### Running invoiceninja using docker on the Raspberry Pi
Set suitable values in your `env` file, based on the [example given in the invoiceninja/invoiceninja project](https://github.com/invoiceninja/invoiceninja/blob/v5-stable/.env.example).
Possibly adapt the values for MYSQL_USER, MYSQL_PASSWORD and MYSQL_DATABASE in the `docker-compose.yml` file and launch the containers from the cloned repo's root with the `docker-compose up -d` command...

You should now be able to access your InvoiceNinja installation running on docker 👍🏽 

Hope this will allow people owning a Raspberry 4 to easily run their own instance of this great software on this very nice (and cheap) little computer 😃

**Comment by turbo124** [comment] 2021-03-25 19:33
@tacticz 

Thank you so much for this detailed post!!!

**Comment by tacticz** [comment] 2021-03-25 23:05
My pleasure!

**Comment by lwj5** [comment] 2021-03-26 01:44
@tacticz the next docker release to invoiceninja/invoiceninja would feature an ARM64 build, would you like to help test it out?

**Comment by tacticz** [comment] 2021-03-26 01:51
@lwj5 certainly, I'll be glad to help!

**Comment by vsisl** [comment] 2021-03-28 21:15
Any plans to develop a version for ARMv7? Most Raspberries run on 32bit Raspberry Pi OS.

**Comment by lwj5** [comment] 2021-03-29 01:15
@vsisl not possible unless alpine packages chromium for ARMv7, which they haven’t done since 3.11.

https://pkgs.alpinelinux.org/packages?name=chromium&branch=v3.13

You can rebuild the image using an older php image based on alpine 3.11.

This belongs in #108

**Comment by manakill** [comment] 2021-04-16 03:25
I'm no expert coder, and I've only hired a coder once, so please bear with me lol. 
I'd be willing to hire someone to help fix this if needed. #https://github.com/invoiceninja/invoiceninja/issues/5386 was is my first attempt at hiring help for my Feature Requests. I'm not trying to rush anything thru, just trying to get a few new features to the point it can be reviewed and merged at earliest convenience, to help myself and in turn help others by making some things more useful. We're restructuring some of our business tools currently and getting this running on Pi 4 ARMv7 would be extremely helpful as we're trying to go with running as much open source as possible. Ideally running in a docker container to stack on a already running Pi 4, but even getting it running on a dedicated Pi 4 would be fine with me. Just let me know if I should look for one outside here, or even one of you are interested I would just need a platform to fund and pay you thru, like Fiverr Pro or whatever.

**Comment by turbo124** [comment] 2021-04-16 03:54
@lwj5 

Is chromium the only blocking issue? If so we can adjust so that snappdf downloads its binary?

**Comment by lwj5** [comment] 2021-04-16 03:59
@turbo124 yes it is. The issue is there's no binary for it, which means snappdf cannot download it as well.

See this for the supported platforms.
https://github.com/beganovich/snappdf/blob/e3657deb39810a82ae9e192cab76b55562539ee1/src/Command/DownloadChromiumCommand.php#L120

Someone can build it from the source and contribute to the alpine packages.

Otherwise, I think Debian buster contains it, which means in addition to alpine, build this docker image on Debian as well.

**Comment by turbo124** [comment] 2021-04-16 04:01
@beganovich thoughts on compiling for ARMv7 ?

**Comment by lwj5** [comment] 2021-04-16 04:17
Alpine 6MB (3MB) vs Debian-slim 70MB (25MB) (compressed). But the layers do not take up extra space if there are other Debian images on that machine thus I feel it's not something to worry about. MariaDB and MySQL are built on Debian-slim :)

Anyway, it's possible to build both. I do not have the bandwidth to do this so someone needs to help contribute.

**Comment by beganovich** [comment] 2021-04-16 11:53
Snappdf is able to use any binary thru any architecture you provide it. The file that @lwj5 sent is only for downloader. 

So if I follow correctly, we want Chromium for armv7 @ alpine? Does this help? Can we somehow get a building recipe for this? https://pkgs.alpinelinux.org/package/v3.11/community/armv7/chromium

Otherwise, we can all save us troubles and just ship the slim version of Debian, which already has chromium in its repos, right?

**Comment by turbo124** [comment] 2021-04-16 21:21
@beganovich correct, so the least friction here would be to get a debian slim build running also.

**Comment by beganovich** [comment] 2021-04-17 17:15
To make our lives easier, I vote for Debian Slim.

**Comment by pixlguru** [comment] 2021-06-17 23:01
cypress runs the tests through chromium, right? 
so basically invoiceninja itself should run just fine on armv7.
conclusion: if you don't need E2E testing capabilities on raspberry platform i 'd suggest to simply disable cypress.

**Comment by turbo124** [comment] 2022-07-13 23:17
@KevoM we really need help for this one, we don't have the internal knowledge for this.

**Comment by pixlguru** [comment] 2022-07-14 05:00
Well... see above.

**Comment by patrix487** [comment] 2022-07-15 14:42
i set up invoice ninja on docker and there were no issues in the logs.
The only issue i have is how to access it.
I have set up nginx manually before and left that part out in my docker-compose.yml file. Though i used the example and cloned the repository. (then i copied my docker-compose.yml file into the dockerfiles folder)
i changed the env file too. The APP_URL is my omv local domain.
I thought when i add a port at the end of the url or add a port in the docker-compose.yml like:
port: ...:80
i will reach my self hosted invoice ninja app via:
http://local.domain:...

this isn't the case. Any help on this?
Sorry for my probably stupid question.

Best Regards

**Closed** 2024-11-24 09:01 UTC
Labels: enhancement, help wanted
