### ISSUE TITLE
Install Error (Invalid default value for 'created_at') using Docker File

### ISSUE THREAD

**Issue by srenon** [invoiceninja/dockerfiles#3] opened 2015-12-19 23:20 UTC
production.ERROR: exception 'PDOException' with message 'SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'created_at'' in /var/www/app/vendor/laravel/framework/src/Illuminate/Database/Connection.php:362

`# php artisan --version`
Laravel Framework version 5.0.33

To get it working I had to 
ssh into the app server
`# cd /var/www/app`
`# composer update`

  - Removing laravel/framework (v5.0.33)
  - Installing laravel/framework (v5.0.34)
  - Downloading: 100%     

Seem to be a framework issue see https://github.com/laravel/framework/issues/3602

**Comment by lalop** [comment] 2015-12-20 11:25
It's seems to depend on the mysql version to.
Are the migration completed ?

**Comment by hillelcoren** [comment] 2015-12-20 11:28
From the other thread... adding strict equals false to the database config file may help.

**Comment by lalop** [comment] 2015-12-20 12:15
@srenon do you use the docker-compose of this repository ?

**Comment by srenon** [comment] 2015-12-20 13:23
@lalop .. this was my installing procedure

Install docker (mac os)
git clone this repo
open Docker Quickstart Terminal
`docker-compose up`
Then open the url and fill out the installation form

**Comment by lalop** [comment] 2015-12-22 17:14
I will try to make a new image in the next days

**Comment by lalop** [comment] 2015-12-24 13:27
I just come to push a new image with the new invoice version, this new one uses laravel 5.0.33 since this is defined into the composer.lock
@srenon I can't reproduce your error, can you try with this new image ?
@hillelcoren there is a good reason to keep composer.lock into the repository ?

**Comment by hillelcoren** [comment] 2015-12-24 13:46
@lalop If we didn't keep the composer.lock file in the repo when users run composer install they may get slightly different versions of the libraries than the ones we've tested with.

**Comment by lalop** [comment] 2015-12-24 13:54
ok I see but if composer.lock is not up-to-date some fix on dependencies ( like laravel here ) can't be deployed with the app.
If you trust the package owner you should define the major and minor version of the package and be open to patch, and remove composer.lock
That is my point of view

**Comment by hillelcoren** [comment] 2015-12-24 14:06
I think these may be two separate issues:
- The dependancies are out of date in our lock file, this should be fixed.  
- My understanding is that the best practice is to check in the lock file. It even advises it in the composer docs: https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

**Comment by hillelcoren** [comment] 2015-12-29 11:55
I've updated the composer.lock file.

**Closed** 2016-04-03 19:16 UTC
